### ISSUE TITLE
Could you please add a LICENSE file?

### ISSUE THREAD

**Issue by mithro** [arpit306/Design-of-Toffoli-Quantum-Gate#1]
There are some instructions on how to add a license file to your repository at https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

If you don't have a preference, I highly recommend using the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) so that if your project is successful it can be eventually merged into Google's SKY130 PDK. (FWIW Apache 2.0 is Google's preferred license for this type of work - see information at https://opensource.google/documentation/reference/thirdparty/licenses#hardware)

**Comment by arpit306** [comment]
done👍
